I key toggles infinite nextTurn
kirpichik/GameOfLife-Curses pull request #3
Opened 2020-12-11 20:12 UTC by big-caballito

just adds convenience

2020-12-12 13:42 UTC, kirpichik requested changes
Hi @big-caballito!

Thanks for your improvement, but I would like to ask for a few changes. I left some of them in the comments to the code, and here's another one:
It would be nice to add smth like that:
`getViewHandler().updateCommandLine("Making steps... Press I for interrupt.");`
before starting infinity steps and clean cmd prompt after interruption.

2020-12-12 13:42 UTC, kirpichik commented on game_handler.cpp
> +void GameManager::step() {
step -> infinitySteps

2020-12-12 13:42 UTC, kirpichik commented on game_handler.cpp
> +  size_t counter = 0;
Remove unused counter

2020-12-12 13:42 UTC, kirpichik commented on game_handler.cpp
> +  for (; true; ++counter) {
Replace with while(true)

2020-12-12 13:47 UTC, kirpichik commented on game_handler.cpp
> +  size_t counter = 0;
Or not delete but display the counter when the user interrupts

2020-12-15 15:17 UTC, merged

2020-12-15 15:17 UTC, big-caballito commented
Sorry it took me so long :shrug:

2020-12-15 15:19 UTC, kirpichik commented
Do not worry and thank you for your contribution!